colorscheme dracula

add-highlighter global/ wrap -word -indent
add-highlighter global/ number-lines -hlcursor
add-highlighter global/ show-matching

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug "andreyorst/smarttab.kak" %{
    set-option global tabstop 4
    set-option global indentwidth 4
    set-option global softtabstop 4
    hook global WinSetOption filetype=.* expandtab
}

plug "lePerdu/kakboard" %{
    declare-option str-list kakboard_paste_keys ""
    declare-option str-list kakboard_copy_keys  ""

    hook global WinCreate        .* %{ kakboard-enable } -once
    hook global WinCreate        .* %{ kakboard-pull-clipboard } -once
    hook global FocusIn          .* %{ kakboard-pull-clipboard }
    hook global RegisterModified \" %{ kakboard-push-clipboard }
}

#eval %sh{kak-lsp --kakoune -s $kak_session}
#map global normal <c-l> ": enter-user-mode lsp<ret>"

#hook global WinSetOption filetype=(rust|python) %{
#    lsp-enable-window
#    lsp-auto-signature-help-enable
#    set global lsp_hover_max_lines 40
#}

plug "occivink/kakoune-filetree" %{
    unmap global normal F
    map global normal f ": filetree<ret>"
    set-option global filetree_find_cmd "fd -t f"
}

plug "occivink/kakoune-buffer-switcher" %{
    map global normal ^ q
    map global normal <a-^> Q
    map global normal q b
    map global normal Q B
    map global normal <a-q> <a-b>
    map global normal <a-Q> <a-B>

    map global normal b ": buffer-switcher<ret>"
}

#plug "caksoylar/kakoune-smooth-scroll" %{
#    hook global WinCreate [^*].* %{ hook -once window WinDisplay .* smooth-scroll-enable }
#}

plug "andreyorst/powerline.kak" defer powerline %{
    powerline-format global "mode_info line_column lsp filetype bufname git"
} config %{
    powerline-start
}
