colorscheme gruvbox

set-option global tabstop 4
set-option global indentwidth 4

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|c|cpp) %{
    lsp-enable-window
    lsp-auto-hover-enable
}

# hook global WinSetOption filetype=rust %{
#     hook window -group rust-inlay-hints BufReload .* rust-analyzer-inlay-hints
#     hook window -group rust-inlay-hints NormalIdle .* rust-analyzer-inlay-hints
#     hook window -group rust-inlay-hints InsertIdle .* rust-analyzer-inlay-hints
#     hook -once -always window WinSetOption filetype=.* %{
#         remove-hooks window rust-inlay-hints
#     }
# }

# lsp-inlay-diagnostics-enable global

set-option global lsp_server_configuration rust.clippy_preference="on"

hook global WinSetOption filetype=<language> %{
    hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
    hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
    hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
    hook -once -always window WinSetOption filetype=.* %{
        remove-hooks window semantic-tokens
    }
}
